# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop', require: false
gem 'rubycritic', require: false
gem 'minitest', '~> 5.25'

gem 'minitest-reporters', "~> 1.7"
gem 'simplecov', require: false, group: :test

